---
title: "Untitled"
output: github_document
---

```{r setup, echo=FALSE}
library(margins)
library(esquisse)
library(tidyverse)
library(moments)
library(dplyr)
library(ggplot2)
library(corrplot)
library(ISLR)
library(car)
library(foreign)
library(ggthemes)
library(colorRamps)
library(foreign)
library(multcomp)
library(survey)
library(lmtest)
library(car)
library(estimatr)
library(gridExtra)
library(gplots)
library(plm)
library(estimatr)
library(lmtest)
source("https://www.r-statistics.com/wp-content/uploads/2010/07/coefplot.r.txt")
library(broom)
library(knitr)
library(sjPlot)
library(stargazer)
install.packages("jtools")
install.packages("devtools")
library(jtools)
library(devtools)
install.packages("huxtable")
library(huxtable)
# Improting the data set
?`estimatr-package`
guns_data<- read.dta("guns.dta")
View(guns_data)
attach(guns_data)
na.omit(guns_data)
# Summary Statistics
summary(guns_data)

```

## Including Code

You can include R code in the document as follows:

```{r}
cor(guns_data[,-15])
```

## Data Exploration/Data Visualization

Correlation Plot

```{r pressure, echo=FALSE}
corrplot.mixed(cor(guns_data[,c(-(15:39))]))
corrplot(cor(guns_data[,c(-(15:39))]),method = "shade")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
pairs(mur~year+incarc_rate+pb1064+pw1064+pm1029+pop+avginc+density)
pairs(rob~year+incarc_rate+pb1064+pw1064+pm1029+pop+avginc+density)
pairs(vio~year+incarc_rate+pb1064+pw1064+pm1029+pop+avginc+density)
pairs(all_crime~year+incarc_rate+pb1064+pw1064+pm1029+pop+avginc+density)
```

```{r}
plot(vio,mur)
plot(vio,rob)
plot(rob,mur)

guns_data$all_crime<-vio+rob+mur
View(guns_data)
attach(guns_data)

stargazer(guns_data[c("vio","mur","rob","incarc_rate","pb1064","pw1064","pm1029","pop","avginc","density","all_crime")], type = "text", title="Descriptive statistics", digits=1, out="descriptive.dox")
names(guns_data)
library(ggplot2)

guns_data$factor_shall<- as.factor(shall)
attach(guns_data)

library(ggplot2)

ggplot(p_dat) +
 aes(x = incarc_rate, y = all_crime) +
 geom_point(size = 1L, colour = "#d8576b") +
 labs(x = "Incarceration Rate(per 100,000)", y = "Total Crime(all_crime)", title = "Scatter Plot Of Incarceration Rate Vs Total Crime") +
 theme_igray()
```

